export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_DATE_RANGE_CHANGE = 'FILTER_DATE_RANGE_CHANGE'

export const FILTER_TITLES_CHANGE = 'FILTER_TITLES_CHANGE'
