export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_FILTER_DATE_FROM = 'CHANGE_FILTER_DATE_FROM'

export const CHANGE_FILTER_DATE_TO = 'CHANGE_FILTER_DATE_TO'

export const CHANGE_SELECTED_IDS = 'CHANGE_SELECTED_IDS'
